apiVersion: v1
kind: Service
metadata:
  name: ms-framevideo-app-service
spec:
  type: ClusterIP
  selector:
    app: ms-framevideo-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
