apiVersion: v1
kind: Service
metadata:
  name: ms-framevideo-app
spec:
  selector:
    app: ms-framevideo-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort  # Para acessar o aplicativo externamente